slurm_config: big
task_type: local_predict
dataset:
  split: test
  video_processor: VideoProcessor
  aligner: COINActionSegmentationAligner
  bert_name: bert-base-uncased
  test_path: data/coin/COIN.json
  meta_processor: COINActionSegmentationMetaProcessor
  vfeat_dir: data/coin/coin_feature_fps30_512
  text_processor: COINActionSegmentationTextProcessor
  num_iso_layer: 12
  sliding_window: 16
  sliding_window_size: 32
  max_video_len: 32
  max_len: 96
fairseq:
  dataset:
    batch_size: 1
    valid_subset: test
    num_workers: 2
  common_eval:
    path: runs/retri/norton/coin/checkpoint_best.pt
model:
  model_cls: MMFusionSeparateActionSegmentation
  mm_encoder_cls: null
  video_encoder_cls: MMBertForTokenClassification
  text_encoder_cls: BertModel
  num_hidden_video_layers: 6
eval:
  save_path: runs/retri/videoclip/coin/
metric: COINActionSegmentationMetric
predictor: COINPredictor
